### ISSUE TITLE
update to version 2.3

### ISSUE THREAD

**Issue by beckermr** [conda-forge/galsim-feedstock#28]
We'll need to update the build.

 - remove scons
 - add python setup.py build_shared_clib
 - copy lib to same spot as scons

link from Mike: https://github.com/GalSim-developers/GalSim/blob/releases/2.3/docs/install_pip.rst#installing-the-c-shared-library

**Comment by beckermr** [comment]
cc @brianv0

**Comment by beckermr** [comment]
We may need a symlink so that libgalsim.so or libgalsim.dylib appears as it did before

**Comment by beckermr** [comment]
cc @erykoff this might have implications for the osx arm build

**Comment by erykoff** [comment]
I've done a little looking into this.  First of all, version 2.3 builds and tests just fine on osx-arm64 (after a small floating point difference was relaxed in one of the tests).  
Second of all, the question of how to move from scons to python is separate from 2.3 (scons is still there, just that this is the end of the line).
However, I had not seen that thing about building the shared library from python.  I'm sure this is exactly what we need and it shouldn't be too hard to make this work without scons as long as we put files in the right place (the same way we're copying the headers at the moment).

**Comment by rmjarvis** [comment]
Version 2.3.0 is released now.  I think it'd be great to try to remove SCons now.  Especially since it's not building properly as is, so there needs to be some kind of edit of the conda-forge build anyway.  I don't particularly understand the build failure. (It's trying to patch the SConstruct file for some reason?)  Might as well go to the kind of build we will need going forward rather than fix the SConstruct build to work, IMO.

So...

The regular kind of shared_library is built by running
```
python setup.py build_shared_clib
```
That puts a libgalsim.2.3.dylib or libgalsim.2.3.so in the directory `build/shared_clib`.  This is done in addition to the normal
```
python setup.py install
```

Then you may still want to do this bit:
```
cp include/GalSim.h "$PREFIX/include"
cp -r include/galsim "$PREFIX/include"
```
The include directory is normally installed in the galsim python module directory, but probably conda should also install it in its standard place too.

The new bit would be to also copy the shared library.  Which I guess should look like:
```
cp build/shared_clib/libgalsim* "$PREFIX/lib"
```
Not sure if PREFIX is still right there or not...

**Comment by erykoff** [comment]
I was working on this yesterday and have a local branch that does this but it doesn’t work for the cross compile. I’ll work it out this weekend. 
But the reason the straight migration doesn’t work is that the patches are no longer needed since they are in 2.3.

**Comment by rmjarvis** [comment]
Not sure if it's helpful, but another way to trigger the shared_clib build is with an environment variable:
```
GALSIM_BUILD_SHARED=1 python setup.py install
```
will do the shared_clib command after doing the normal install.

The problem I had when trying this locally using pip as the driver (since Matt said that's what we were supposed to do) was finding the `build` directory, since pip likes to use a transient temp directory to do the build, so it disappears once the wheel is made.

But maybe you have a solution for this already?  Or I was thinking it would be ok to have pip build and install the wheel, but then still follow up with a normal `python setup.py shared_clib` command to build the shared library in an accessible location.

**Comment by beckermr** [comment]
You use pip to build the python package. For the shared lib a direct call of the setup.py is fine.

**Comment by beckermr** [comment]
The last thing you said!

**Comment by rmjarvis** [comment]
OK.  Then I think it should be fine.  Modulo Eli's problem with cross-compiling...

**Comment by erykoff** [comment]
Yeah. That last thing works for native builds. Haven’t had a chance to look at the cross stuff today.
